ALTER TABLE "StudentGuardian"
ADD COLUMN "isPrimary" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "canReceiveNotice" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "canSubmitHomework" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "canViewGrowth" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "status" TEXT NOT NULL DEFAULT 'active',
ADD COLUMN "remark" TEXT,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
